extends Reference

const IDENTIFIER = "IDENTIFIER"
const BLOCKED_KEYWORD = "BLOCKED_KEYWORD"
const BLOCKED_FUNC = "BLOCKED_FUNC"
const GDSCRIPT_CONST = "GDSCRIPT_CONST"
const GDSCRIPT_FUNC = "GDSCRIPT_FUNC"

const LINEBREAK = "LINEBREAK"
const DOT = "DOT"
const COMMA = "COMMA"
const COLON = "COLON"

const COMMENT = "COMMENT"
const COMMENT_CONT = "COMMENT_CONT"

const STRING = "STRING"
const STRING_MULTILINE_CONT = "STRING_CONT"
const INT = "INT"
const FLOAT = "FLOAT"
const INLINE_TEXT = "TEXT"

const OPEN_PARENTHESIS = "OPEN_PAR"
const CLOSE_PARENTHESIS = "CLOSE_PAR"

const OPEN_BRACKET = "OPEN_BRACKET"
const CLOSE_BRACKET = "CLOSE_BRACKET"

const OPEN_BRACE = "OPEN_BRACE"
const CLOSE_BRACE = "CLOSE_BRACE"

const OPENING_TOKENS := [
	OPEN_PARENTHESIS,
	OPEN_BRACE,
	OPEN_BRACKET
]

const CLOSING_TOKENS := {
	OPEN_PARENTHESIS: CLOSE_PARENTHESIS,
	OPEN_BRACE: CLOSE_BRACE,
	OPEN_BRACKET: CLOSE_BRACKET
}

const END_OF_FILE = "END_FILE"

const ASSIGN = "ASSIGN"


const OPERATOR = "OPERATOR"
const INVALID_OPERATOR = "INVALID_OPERATOR"

# keywords
const KEYWORD_TRUE = "TRUE"
const KEYWORD_FALSE = "FALSE"
const KEYWORD_RETURN = "RETURN"
const KEYWORD_NOT = "NOT"
const KEYWORD_OR = "OR"
const KEYWORD_AND = "AND"
const KEYWORD_IN = "IN"
const KEYWORD_AS = "AS"
const KEYWORD_IF = "IF"
const KEYWORD_ELSE = "ELSE"
const KEYWORD_ELIF = "ELIF"

const CONDITIONALS = [
	KEYWORD_IF,
	KEYWORD_ELSE,
	KEYWORD_ELIF
]
