extends Reference

const IDENTIFIER = "IDENTIFIER"
const RESERVED_KEYWORD = "RESERVED_KEYWORD"
const OPERATOR = "OPERATOR"

const STRING = "STRING"
const INT = "INT"
const FLOAT = "FLOAT"
const RAW_TEXT = "TEXT"


const OPEN_PARENTHESIS = "OPEN_PARENTHESIS"
const CLOSE_PARENTHESIS = "CLOSE_PARENTHESIS"

const OPEN_BRACKET = "OPEN_BRACKET"
const CLOSE_BRACKET = "CLOSE_BRACKET"

const OPEN_BRACE = "OPEN_BRACE"
const CLOSE_BRACE = "CLOSE_BRACE"

const ASSIGN = "ASSIGN"

const DOT = "DOT"
const COMMA = "COMMA"
